name: shortwave
version: 3.0.0
summary: Find and listen to internet radio stations
description: |
 Shortwave is an internet radio player that provides access to a station
 database with over 25,000 stations.
base: core22
grade: stable
confinement: strict
license: GPL-3.0+

architectures:
  - amd64
  - arm64

slots:
  # for GtkApplication registration
  shortwave:
    interface: dbus
    bus: session
    name: de.haeckerfelix.Shortwave
  mpris:
    name: Shortwave

apps:
  shortwave:
    command: usr/bin/shortwave
    extensions: [gnome]
    desktop: usr/share/applications/de.haeckerfelix.Shortwave.desktop
    common-id: de.haeckerfelix.Shortwave
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/local/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    plugs:
      - home
      - network
      - network-status
      - audio-playback
      - screen-inhibit-control
    slots:
      - mpris

parts:
  shumate:
    source: https://gitlab.gnome.org/GNOME/libshumate/-/archive/1.0.0.alpha.1/libshumate-1.0.0.alpha.1.tar.bz2
    plugin: meson
    meson-parameters:
      - --wrap-mode=nodownload
    build-packages:
      - meson
      - ninja-build
      - libgtk-4-dev
      - libsqlite3-dev
      - libsoup-3.0-dev
      - gi-docgen

  shortwave:
    after: [shumate]
    source: https://gitlab.gnome.org/World/Shortwave/-/archive/3.0.0/Shortwave-3.0.0.tar.bz2
    plugin: meson
    meson-parameters:
      - --prefix=/snap/shortwave/current/usr
    parse-info: [usr/share/metainfo/de.haeckerfelix.Shortwave.xml]
    organize:
      snap/shortwave/current: .
    build-packages:
      - intltool
      - gettext
      - gnome-common
      - rustc
      - libsqlite3-dev
      - libssl-dev
      - appstream
      - libappstream-glib-dev
      - libappstream-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libadwaita-1-dev
      - libhandy-1-dev
      - cargo
      - git
      - desktop-file-utils
    stage-packages:
      - freeglut3
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - liba52-0.7.4
      - libadwaita-1-0
      - libaom3
      - libass9
      - libbs2b0
      - libcdio19
      - libchromaprint1
      - libdc1394-25
      - libdca0
      - libde265-0
      - libdvdnav4
      - libdvdread8
      - libfaad2
      - libflite1
      - libfluidsynth3
      - libfreeaptx0
      - libgl1
      - libglu1-mesa
      - libglvnd0
      - libglx0
      - libgme0
      - libgsm1
      - libgstreamer-plugins-bad1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libhandy-1-0
      - libkate1
      - libldacbt-enc2
      - liblilv-0-0
      - libltc11
      - libmjpegutils-2.1-0
      - libmodplug1
      - libmpcdec6
      - libmpeg2-4
      - libopenal1
      - libopencore-amrnb0
      - libopencore-amrwb0
      - libopenexr25
      - libopenh264-6
      - libopenni2-0
      - liborc-0.4-0
      - libqrencode4
      - libsbc1
      - libsidplay1v5
      - libsoundtouch1
      - libspandsp2
      - libsrt1.4-gnutls
      - libsrtp2-1
      - libusb-1.0-0
      - libvo-aacenc0
      - libvo-amrwbenc0
      - libx264-163
      - libx265-199
      - libzbar0
      - libzvbi0
    override-pull: |
      craftctl default
      # snapd can't use a name like de.haeckerfelix.Shortwave for mpris
      # (since it contains periods) so instead make this just Shortwave
      sed -i 's/config::APP_ID.to_string()/config::NAME.to_string()/' src/audio/controller/mpris_controller.rs

    override-prime: |
      set -eu
      craftctl default
      # Fix-up application icon lookup
      sed -i.bak -e 's|^Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/de.haeckerfelix.Shortwave.svg|' usr/share/applications/de.haeckerfelix.Shortwave.desktop
