name: shortwave
version: 4.0.1
summary: Find and listen to internet radio stations
description: |
 Shortwave is an internet radio player that provides access to a station
 database with over 25,000 stations.
base: core24
grade: stable
confinement: strict
license: GPL-3.0+

# gnome extension snap is only available on amd64/arm64/armhf
platforms:
  amd64:
  arm64:
  armhf:

layout:
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

slots:
  # for GtkApplication registration
  shortwave:
    interface: dbus
    bus: session
    name: de.haeckerfelix.Shortwave
  mpris:
    name: Shortwave

apps:
  shortwave:
    command: usr/bin/shortwave
    command-chain:
    - bin/gpu-2404-wrapper
    extensions: [gnome]
    desktop: usr/share/applications/de.haeckerfelix.Shortwave.desktop
    common-id: de.haeckerfelix.Shortwave
    plugs:
      - gpu-2404
      - home
      - network
      - network-status
      - audio-playback
      - screen-inhibit-control
    slots:
      - mpris


parts:
  gtk4:
    source: https://download.gnome.org/sources/gtk/4.16/gtk-4.16.3.tar.xz
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - glslc
    override-pull: |
      craftctl default
      sed -i "s/'redundant-decls',/#'redundant-decls',/" meson.build

  shumate:
    source: https://gitlab.gnome.org/GNOME/libshumate/-/archive/1.3.0/libshumate-1.3.0.tar.bz2
    plugin: meson
    meson-parameters:
      - --buildtype=release
      - --prefix=/usr
      - --strip
      - --wrap-mode=nodownload
      - -Dgir=false
      - -Dvapi=false
      - -Dgtk_doc=false
    build-packages:
      - gperf
      - libprotobuf-c-dev
    stage-packages:
      - libprotobuf-c1
      - libsysprof-6-6

  shortwave:
    after: [gtk4, shumate]
    source: https://gitlab.gnome.org/World/Shortwave/-/archive/$CRAFT_PROJECT_VERSION/Shortwave-$CRAFT_PROJECT_VERSION.tar.bz2
    plugin: meson
    meson-parameters:
      - --prefix=/snap/shortwave/current/usr
    parse-info: [usr/share/metainfo/de.haeckerfelix.Shortwave.xml]
    organize:
      snap/shortwave/current: .
    build-snaps:
      - rustup
    build-packages:
      - libssl-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - git
    stage-packages:
      - libproxy1v5
    override-pull: |
      craftctl default
      # snapd can't use a name like de.haeckerfelix.Shortwave for mpris
      # (since it contains periods) so instead make this just Shortwave
      sed -i 's/Player::builder(config::APP_ID)/Player::builder(config::NAME)/' src/audio/mpris.rs

    override-build: |
      rustup default stable
      craftctl default

    override-prime: |
      set -eu
      craftctl default
      # Fix-up application icon lookup
      sed -i.bak -e 's|^Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/de.haeckerfelix.Shortwave.svg|' usr/share/applications/de.haeckerfelix.Shortwave.desktop

    stage:
      # don't duplicate bits from the gtk4 or shumate parts
      - -usr/lib/x86_64-linux-gnu/gtk-4.0/4.0.0/printbackends/libprintbackend-file.so
      - -usr/lib/x86_64-linux-gnu/libgtk-4.so.1

  gstreamer-plugins:
    after: [shortwave]
    plugin: nil
    build-snaps:
      - core24
      - gnome-46-2404
    stage-packages:
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
    override-build: |
      set -eux
      craftctl default
      for snap in "core24" "gnome-46-2404"; do
        cd /snap/$snap/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
        find . -type f,l -name "*.so*" -exec bash -c "rm -f $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/{}*" \;
      done
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/*.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/*/*.so*

  gpu-2404:
    after: [gstreamer-plugins]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
    - bin/gpu-2404-wrapper

