name: shortwave
version: 3.2.0
summary: Find and listen to internet radio stations
description: |
 Shortwave is an internet radio player that provides access to a station
 database with over 25,000 stations.
base: core22
grade: stable
confinement: strict
license: GPL-3.0+

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64

slots:
  # for GtkApplication registration
  shortwave:
    interface: dbus
    bus: session
    name: de.haeckerfelix.Shortwave
  mpris:
    name: Shortwave

apps:
  shortwave:
    command: usr/bin/shortwave
    extensions: [gnome]
    desktop: usr/share/applications/de.haeckerfelix.Shortwave.desktop
    common-id: de.haeckerfelix.Shortwave
    plugs:
      - home
      - network
      - network-status
      - audio-playback
      - screen-inhibit-control
    slots:
      - mpris

parts:
  shumate:
    source: https://gitlab.gnome.org/GNOME/libshumate/-/archive/1.0.3/libshumate-1.0.3.tar.bz2
    plugin: meson
    meson-parameters:
      - --buildtype=release
      - --prefix=/usr
      - --strip
      - --wrap-mode=nodownload
      - -Dgir=false
      - -Dvapi=false
      - -Dgtk_doc=false

  shortwave:
    after: [shumate]
    source: https://gitlab.gnome.org/World/Shortwave/-/archive/3.2.0/Shortwave-3.2.0.tar.bz2
    plugin: meson
    meson-parameters:
      - --prefix=/snap/shortwave/current/usr
    parse-info: [usr/share/metainfo/de.haeckerfelix.Shortwave.xml]
    organize:
      snap/shortwave/current: .
    build-packages:
      - rustc
      - libssl-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - cargo
      - git
    override-pull: |
      craftctl default
      # snapd can't use a name like de.haeckerfelix.Shortwave for mpris
      # (since it contains periods) so instead make this just Shortwave
      sed -i 's/config::APP_ID.to_string()/config::NAME.to_string()/' src/audio/controller/mpris_controller.rs

    override-prime: |
      set -eu
      craftctl default
      # Fix-up application icon lookup
      sed -i.bak -e 's|^Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/de.haeckerfelix.Shortwave.svg|' usr/share/applications/de.haeckerfelix.Shortwave.desktop

  gstreamer-plugins:
    plugin: nil
    build-snaps:
      - core22
      - gnome-42-2204
    stage-packages:
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
    override-build: |
      set -eux
      craftctl default
      for snap in "core22" "gnome-42-2204"; do
        cd /snap/$snap/current/usr/lib/$CRAFT_ARCH_TRIPLET
        find . -type f,l -name "*.so*" -exec bash -c "rm -f $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET/{}*" \;
      done
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET/*.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET/*/*.so*

