name: shortwave
version: 3.0.0
summary: Find and listen to internet radio stations
description: |
 Shortwave is an internet radio player that provides access to a station
 database with over 25,000 stations.
base: core22
grade: stable
confinement: strict
license: GPL-3.0+

slots:
  # for GtkApplication registration
  shortwave:
    interface: dbus
    bus: session
    name: de.haeckerfelix.Shortwave
  mpris:
    name: Shortwave

apps:
  shortwave:
    environment:
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
    command: shortwave
    extensions: [gnome]
    desktop: usr/share/applications/de.haeckerfelix.Shortwave.desktop
    common-id: de.haeckerfelix.Shortwave
    plugs:
      - home
      - network
      - network-status
      - audio-playback
      - screen-inhibit-control
    slots:
      - mpris

parts:
  shumate:
    source: https://gitlab.gnome.org/GNOME/libshumate/-/archive/1.0.0.alpha.1/libshumate-1.0.0.alpha.1.tar.bz2
    plugin: meson
    meson-parameters:
      - --wrap-mode=nodownload
    build-packages:
      - meson
      - ninja-build
      - libgtk-4-dev
      - libsqlite3-dev
      - libsoup-3.0-dev
      - gi-docgen

  shortwave:
    after: [shumate]
    source: https://gitlab.gnome.org/World/Shortwave/-/archive/3.0.0/Shortwave-3.0.0.tar.bz2
    plugin: meson
    meson-parameters:
      - --prefix=/snap/shortwave/current/usr
    parse-info: [usr/share/metainfo/de.haeckerfelix.Shortwave.xml]
    organize:
      snap/shortwave/current: .
    build-packages:
      - intltool
      - gettext
      - gnome-common
      - rustc
      - libsqlite3-dev
      - libssl-dev
      - appstream
      - libappstream-glib-dev
      - libappstream-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libadwaita-1-dev
      - libhandy-1-dev
      - cargo
      - git
      - desktop-file-utils
    stage-packages:
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - libglu1-mesa
      - freeglut3
      - libhandy-1-0
      - libadwaita-1-0
      - liborc-0.4-0
      - libgl1
      - libglvnd0
      - libglx0
    override-pull: |
      craftctl default
      # snapd can't use a name like de.haeckerfelix.Shortwave for mpris
      # (since it contains periods) so instead make this just Shortwave
      sed -i 's/config::APP_ID.to_string()/config::NAME.to_string()/' src/audio/controller/mpris_controller.rs

    override-prime: |
      set -eu
      craftctl default
      # Fix-up application icon lookup
      sed -i.bak -e 's|^Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/de.haeckerfelix.Shortwave.svg|' usr/share/applications/de.haeckerfelix.Shortwave.desktop

  wrapper:
    plugin: dump
    source: wrapper
