name: shortwave
version: 2.0.1
summary: Find and listen to internet radio stations
description: |
 Shortwave is an internet radio player that provides access to a station
 database with over 25,000 stations.
base: core20
grade: stable
confinement: strict
license: GPL-3.0+

slots:
  # for GtkApplication registration
  shortwave:
    interface: dbus
    bus: session
    name: de.haeckerfelix.Shortwave
  mpris:
    name: Shortwave

environment:
  XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS

apps:
  shortwave:
    extensions: [gnome-3-38]
    command: shortwave
    desktop: usr/share/applications/de.haeckerfelix.Shortwave.desktop
    plugs:
      - home
      - network
      - audio-playback
    slots:
      - mpris

parts:
  shortwave:
    source: https://gitlab.gnome.org/World/Shortwave/uploads/1c5adbe8c3181b2ba81d944a8f9a889d/shortwave-2.0.1.tar.xz
    plugin: meson
    meson-parameters: [--prefix=/snap/shortwave/current/usr]
    organize:
      snap/shortwave/current/usr: usr
    build-packages:
      - intltool
      - gettext
      - gnome-common
      - rustc
      - libsqlite3-dev
      - libssl-dev
      - appstream
      - libappstream-glib-dev
      - libappstream-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libhandy-0.0-dev
      - cargo
      - git
    stage-packages:
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - libglu1-mesa
      - freeglut3
      - libhandy-0.0-0
      - liborc-0.4-0
      - libgl1
      - libglvnd0
      - libglx0
    override-build: |
      # snapd can't use a name like de.haeckerfelix.Shortwave for mpris
      # (since it contains periods) so instead make this just Shortwave
      sed -i 's|MprisPlayer::new(config::APP_ID.to_string()|MprisPlayer::new(config::NAME.to_string()|' ../src/src/audio/controller/mpris_controller.rs
      # cope with deleted branch on source repo
      sed -i 's|branch = "update_cargo_version"|rev = "62e7abf44d419cf3fe83da64285f2905da4e333e"|' ../src/Cargo.toml
      sed -i 's|branch=update_cargo_version|branch=master|' ../src/Cargo.lock
      snapcraftctl build

    override-prime: |
      set -eu
      snapcraftctl prime
      # Fix-up application icon lookup
      sed -i.bak -e 's|^Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/de.haeckerfelix.Shortwave.svg|' usr/share/applications/de.haeckerfelix.Shortwave.desktop

  wrapper:
    plugin: dump
    source: wrapper
